### ISSUE TITLE
Renaming nodes in guide/phylogenetic trees

### ISSUE THREAD

**Issue by lanzv** [Genome-of-Melody/chantlab_backend#17]
Ensure all tree nodes have correct name formats, including relatable information - sources in case of concatenated, incipit+source+id in case of not concatenated mode. Chant/source names should be returned with spaces, and tree node names should replace spaces with underscores.

**Comment by lanzv** [comment]
Solved by commits [concatenated alignment by cantus id groups, remove ids (replaced by siglum etc..) from guide tree node names](https://github.com/Genome-of-Melody/chantlab_backend/commit/ea7968682a1d379fa8dd040923b1a01b0413fb97), [return chant/source names with spaces (without '_'), replace spaces by '_' only for guide tree](https://github.com/Genome-of-Melody/chantlab_backend/commit/9c048970a25f2c4de873ae1c1e4566ac68f183b9), [support passing any alignment names to mr bayes endpoint](https://github.com/Genome-of-Melody/chantlab_backend/commit/a49652751a6b79343a63923c7884c3ff657123fa)

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified ChantProcessor.build_chant_newick_name method to include incipit, source, and ID. Updated mrbayes_volpiano view to use the new method for generating tree node names. Ensured spaces are replaced with underscores in tree node names.

You can review changes in this commit: https://github.com/jjyutm4532/Genome-of-Melody-chantlab_backend-17/commit/59e626f95e3cee20f211bba2b0c442ebcd0f2459.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
