### ISSUE TITLE
Use Gustavo's better substitution matrix for the MSA step

### ISSUE THREAD

**Issue by hajicj** [Genome-of-Melody/chantlab_backend#3]
Part of #1 

The matrix is passed to mafft via the `--textmatrix` argument. See the divtime_christmas repo, step `00_tree_inference`.

**Comment by lanzv** [comment]
Related to commit [mafft --textmatrix argument](https://github.com/Genome-of-Melody/chantlab_backend/commit/b9e8763ae70018c7e060040a10380968e1a3ea9d)
