### ISSUE TITLE
App should keep last alignment in temp storage

### ISSUE THREAD

**Issue by hajicj** [Genome-of-Melody/chantlab_backend#4]
This becomes relevant when you want to cycle between the alignment and the phylogeny, or just going back and forth, or refreshing by accident, etc.

Until the user specifies a new set of chants that should be aligned, whenever they land on the `/align` page, the last computed alignment (if it exists) should be loaded, instead of re-computing it in the back-end.

This implies caching it in local storage under some 'default' name via the `AlignmentManagementService`, and invalidating this cache as soon as the chant selection in `AlignmentService` gets changed.

(The same thing should be done for the phylogeny inference result, as #1 gets implemented.)

**Comment by lanzv** [comment]
Implemented as part of the frontend - [Cache Alignment Data for Parsed Chants to Avoid Recomputations](https://github.com/Genome-of-Melody/chantlab_frontend/issues/19)
